- hosts: all
  tasks:
    - name: installing git
      command: yum install git -y

    - name: installing httpd
      yum: name=httpd state=present
    - name: installing docker
      yum: name=docker state=present
